### ISSUE TITLE
Missing commands

### ISSUE THREAD

**Issue by focalor** [focalor/utobot#1]
- [x] DeleteProv
- [x] DeleteNick
- [x] addspell
- [x] Help
- [x] Army xx.xx
- [x] !armyadd {xx.yy} {comment/nick}

moved other commands to their own issues

**Comment by SephirothWarcry** [comment]
!armyadd «xx.yy» «comment/nick»
!orderadd «active duration» «order»
!orderdel «number»
!orders
!personalorder «nick» «active duration» «order»
!raceorder «race» «active duration» «order»  should check nick for race and show orders in that case

**Comment by SephirothWarcry** [comment]
For good team spirit:
!quote {number}
!quoteadd {user} {quote}
and then make the bot take a random quote per tick update to display :D

**Comment by focalor** [comment]
Added your suggestions, moved some to their own issues, #4, #5, #6

**Comment by SephirothWarcry** [comment]
!seen <nick> reports when the bot last saw someone quit. just requires a read along with a push on quit msgs (could also include nick changes... thats up to you)
